# Generated by Django 3.0.2 on 2020-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=30)),
                ('Color', models.CharField(max_length=20)),
                ('Image', models.FileField(upload_to='')),
                ('Size', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Details', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
