# Generated by Django 3.0.2 on 2020-07-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='product',
        ),
    ]
