# Generated by Django 3.0.2 on 2020-07-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriesmodel',
            table='categories',
        ),
    ]
