# Generated by Django 3.0.2 on 2020-08-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField()),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_brand', models.CharField(max_length=100)),
                ('pro_quantity', models.CharField(max_length=100)),
                ('pro_price', models.IntegerField()),
                ('pro_size', models.IntegerField()),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
